version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      deps:
        patterns:
          - '*'

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    groups:
      deps:
        patterns:
          - '*'
